### ISSUE TITLE
Exception: Can't create Version from next

### ISSUE THREAD

**Issue by zeke** [replicate/replicate-python#13]
This code:

```py
replicate.models.get("zeke/haiku-standard").predict(seed=123)
```

Produces this result:

```
python-3.10.4 ∴ python test.py
model: zeke/haiku-standard
Traceback (most recent call last):
  File "/Users/z/git/replicate/replicate-python-in-anger/test.py", line 49, in <module>
    test_simple_model()
  File "/Users/z/git/replicate/replicate-python-in-anger/test.py", line 12, in test_simple_model
    prediction = model.predict(seed=123)
  File "/Users/z/.pyenv/versions/python-3.10.4/lib/python3.10/site-packages/replicate/model.py", line 14, in predict
    versions = self.versions.list()
  File "/Users/z/.pyenv/versions/python-3.10.4/lib/python3.10/site-packages/replicate/version.py", line 56, in list
    return [self.prepare_model(obj) for obj in resp.json()]
  File "/Users/z/.pyenv/versions/python-3.10.4/lib/python3.10/site-packages/replicate/version.py", line 56, in <listcomp>
    return [self.prepare_model(obj) for obj in resp.json()]
  File "/Users/z/.pyenv/versions/python-3.10.4/lib/python3.10/site-packages/replicate/collection.py", line 38, in prepare_model
    raise Exception("Can't create %s from %s" % (self.model.__name__, attrs))
Exception: Can't create Version from next
```

On these versions:

```
$ python --version
Python 3.10.4

$ cat requirements.txt | grep replicate
replicate==0.0.1a6
```

This was working yesterday. Not sure what regressed but filing a ticket so I don't forget.

cc @bfirsh

**Comment by zeke** [comment]
Ah of course! The pagination.
