### ISSUE TITLE
unsupported operand type(s) for |: '_SpecialForm' and '_GenericAlias'

### ISSUE THREAD

**Issue by zeke** [replicate/replicate-python#2]
Installation:

```
cog ∴ python setup.py install  
/Users/z/.pyenv/versions/3.8.12/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
/Users/z/.pyenv/versions/3.8.12/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running install_lib
running install_egg_info
Removing /Users/z/.pyenv/versions/cog/lib/python3.8/site-packages/replicate-0.1.0-py3.8.egg-info
Writing /Users/z/.pyenv/versions/cog/lib/python3.8/site-packages/replicate-0.1.0-py3.8.egg-info
```

My code:

```py
import replicate
```

My env:

```
 ∴ python --version && uname -a
Python 3.8.12
Darwin Ezekiels-MBP.localdomain 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64
```

Output:

```
∴ python smoke-test.py 

Traceback (most recent call last):
  File "smoke-test.py", line 1, in <module>
    import replicate
  File "/Users/z/git/replicate/replicate-python/replicate/__init__.py", line 1, in <module>
    from .client import Client
  File "/Users/z/git/replicate/replicate-python/replicate/client.py", line 4, in <module>
    from replicate.model import ModelCollection
  File "/Users/z/git/replicate/replicate-python/replicate/model.py", line 6, in <module>
    from replicate.version import Version
  File "/Users/z/git/replicate/replicate-python/replicate/version.py", line 9, in <module>
    class Version(BaseModel):
  File "/Users/z/git/replicate/replicate-python/replicate/version.py", line 15, in Version
    def predict(self, **kwargs) -> Any | Iterator[Any]:
TypeError: unsupported operand type(s) for |: '_SpecialForm' and '_GenericAlias'
```

cc @bfirsh

**Comment by khaquachtrong74** [comment]
Can I get sizeof "SpecialGenericAlias" with the easy way?
