### ISSUE TITLE
ModelError: Unknown error handling prediction.

### ISSUE THREAD

**Issue by tassa-yoniso-manasi-karoto** [replicate/replicate-python#262]
Replicate v0.22.0

```
Traceback (most recent call last):
  File "/home/voiduser/go/src/sentences/whisper.py", line 93, in <module>
    main()
  File "/home/voiduser/go/src/sentences/whisper.py", line 62, in main
    whispered = run_whisper(prow, path)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/replicate/lib/python3.12/site-packages/wrapt_timeout_decorator/wrapt_timeout_decorator.py", line 146, in wrapper
    return wrapped_with_timeout(wrap_helper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/replicate/lib/python3.12/site-packages/wrapt_timeout_decorator/wrapt_timeout_decorator.py", line 153, in wrapped_with_timeout
    return wrapped_with_timeout_signals(wrap_helper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/replicate/lib/python3.12/site-packages/wrapt_timeout_decorator/wrapt_timeout_decorator.py", line 161, in wrapped_with_timeout_signals
    return wrap_helper.wrapped(*wrap_helper.args, **wrap_helper.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/voiduser/go/src/sentences/whisper.py", line 32, in run_whisper
    return replicate.run(model_version, input={"audio": Path(audio), "language": "th"})["transcription"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/replicate/lib/python3.12/site-packages/replicate/client.py", line 147, in run
    return run(self, ref, input, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/replicate/lib/python3.12/site-packages/replicate/run.py", line 52, in run
    raise ModelError(prediction.error)
replicate.exceptions.ModelError: Unknown error handling prediction.
```

**Comment by tassa-yoniso-manasi-karoto** [comment]
model was openai/whisper:4d50797290df275329f202e48c76360b3f22b08d28c196cbc54600319435f8d2
my script batch transcribe thousands of audio files so I can't trace back with prediction it was

**Comment by mattt** [comment]
@tassa-yoniso-manasi-karoto Thanks for clarifying. My recommendation would be to add a `try / except` for `ModelError` and log any problems as they occur. If / when you do, you might [open an issue in the model repo](https://github.com/replicate/cog-whisper) with that information.
