### ISSUE TITLE
httpx.ReadTimeout during prediction.async_reload()

### ISSUE THREAD

**Issue by scottyeung** [replicate/replicate-python#345]
Hi there, I think there's a prediction took longer than expected as it's done via a cog instance which needs a cold boot. Is there a way to increase the timeout of the prediction? 

```
2024-09-03 02:37:40.403	
httpx.ReadTimeout
2024-09-03 02:37:40.403	
raise mapped_exc(message) from exc
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
2024-09-03 02:37:40.403	
self.gen.throw(value)
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
2024-09-03 02:37:40.403	
with map_httpcore_exceptions():
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
response = await self._wrapped_transport.handle_async_request(request)  # type: ignore
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/replicate/client.py", line 301, in handle_async_request
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
response = await transport.handle_async_request(request)
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1776, in _send_single_request
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
response = await self._send_single_request(request)
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
response = await self._send_handling_redirects(
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
response = await self._send_handling_auth(
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1674, in send
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
return await self.send(request, auth=auth, follow_redirects=follow_redirects)
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1585, in request
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
resp = await self._async_client.request(method, path, **kwargs)
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/replicate/client.py", line 93, in _async_request
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
resp = await self._client._async_request("GET", f"/v1/predictions/{id}")
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/replicate/prediction.py", line 367, in async_get
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
updated = await self._client.predictions.async_get(self.id)
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/replicate/prediction.py", line 232, in async_reload
2024-09-03 02:37:40.403	
await prediction.async_reload()
2024-09-03 02:37:40.403	
File "/app/app/services/transcription_service.py", line 473, in _run_replicate_youtube
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
return await self._run_replicate_youtube(task_id, youtube_url, db)
2024-09-03 02:37:40.403	
File "/app/app/services/transcription_service.py", line 445, in _process_youtube
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
replicate_result = await self._process_youtube(task_id, youtube_url, db)
2024-09-03 02:37:40.403	
File "/app/app/services/transcription_service.py", line 429, in transcribe_youtube
2024-09-03 02:37:40.403	
Traceback (most recent call last):
2024-09-03 02:37:40.403	
The above exception was the direct cause of the following exception:
2024-09-03 02:37:40.403	
httpcore.ReadTimeout
2024-09-03 02:37:40.403	
raise to_exc(exc) from exc
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2024-09-03 02:37:40.403	
self.gen.throw(value)
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
2024-09-03 02:37:40.403	
with map_exceptions(exc_map):
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 32, in read
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
data = await self._network_stream.read(
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 224, in _receive_event
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
event = await self._receive_event(timeout=timeout)
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_headers
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
) = await self._receive_response_headers(**kwargs)
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 113, in handle_async_request
2024-09-03 02:37:40.403	
raise exc
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
return await self._connection.handle_async_request(request)
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
response = await connection.handle_async_request(
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
2024-09-03 02:37:40.403	
raise exc from None
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
2024-09-03 02:37:40.403	
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-03 02:37:40.403	
resp = await self._pool.handle_async_request(req)
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
2024-09-03 02:37:40.403	
yield
2024-09-03 02:37:40.403	
File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
2024-09-03 02:37:40.403	
Traceback (most recent call last):
```

**Comment by mattt** [comment]
Hi @scottyeung. That's not what I'd expect to happen. Can you share the prediction ID? Have you seen this happen again since you opened this issue?

**Comment by scottyeung** [comment]
> Hi @scottyeung. That's not what I'd expect to happen. Can you share the prediction ID? Have you seen this happen again since you opened this issue?

Thanks @mattt. After I put it into a try-block today I haven't seen it so far. Would definitely keep you posted in this thread!

**Comment by mattt** [comment]
Glad to hear it, @scottyeung. I'm going to close this issue for now, but please do let me know if you see anything like this again.
