### ISSUE TITLE
image failed to produce saying not enough memory

### ISSUE THREAD

**Issue by bsandmg** [replicate/replicate-python#351]
Using seed: 33636
Prompt: Create an realistic anime-style portrait of a black female character,  with the following characteristics:
Clean, smooth lines
Vibrant, soft colors (like pastels)
Slightly smiling facial features
expressive eyes with highlights
Soft shading for depth
long hair, lots of curls, green eyes
A warm, friendly smile
Dressed in dark suit, talking to students in auditorium, standing in behind a  podium speaking into a microphone
[!] Resizing input image from 2048x2560 to 2048x2560
[!] img2img mode
[!] Using schnell model for img2img
Using schnell model
Loaded LoRAs in 9.21s
  0%|          | 0/16 [00:00<?, ?it/s]
  6%|▋         | 1/16 [00:04<01:05,  4.37s/it]
 12%|█▎        | 2/16 [00:09<01:10,  5.04s/it]
 19%|█▉        | 3/16 [00:15<01:08,  5.26s/it]
 25%|██▌       | 4/16 [00:20<01:04,  5.36s/it]
 31%|███▏      | 5/16 [00:26<00:59,  5.41s/it]
 38%|███▊      | 6/16 [00:31<00:54,  5.45s/it]
 44%|████▍     | 7/16 [00:37<00:49,  5.47s/it]
 50%|█████     | 8/16 [00:42<00:43,  5.48s/it]
 56%|█████▋    | 9/16 [00:48<00:38,  5.49s/it]
 62%|██████▎   | 10/16 [00:54<00:33,  5.50s/it]
 69%|██████▉   | 11/16 [00:59<00:27,  5.52s/it]
 75%|███████▌  | 12/16 [01:05<00:22,  5.52s/it]
 81%|████████▏ | 13/16 [01:10<00:16,  5.53s/it]
 88%|████████▊ | 14/16 [01:16<00:11,  5.53s/it]
 94%|█████████▍| 15/16 [01:21<00:05,  5.54s/it]
100%|██████████| 16/16 [01:27<00:00,  5.54s/it]
100%|██████████| 16/16 [01:27<00:00,  5.45s/it]
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/cog/server/worker.py", line 354, in _predict
result = predict(**payload)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "/src/predict.py", line 391, in predict
output = pipe(**common_args, **flux_kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/diffusers/pipelines/flux/pipeline_flux_img2img.py", line 835, in __call__
image = self.vae.decode(latents, return_dict=False)[0]
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
return method(self, *args, **kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 321, in decode
decoded = self._decode(z).sample
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 292, in _decode
dec = self.decoder(z)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/diffusers/models/autoencoders/vae.py", line 337, in forward
sample = up_block(sample, latent_embeds)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 2750, in forward
hidden_states = upsampler(hidden_states)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/diffusers/models/upsampling.py", line 169, in forward
hidden_states = F.interpolate(hidden_states, scale_factor=2.0, mode="nearest")
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/torch/nn/functional.py", line 4050, in interpolate
return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 15.00 GiB. GPU 0 has a total capacity of 79.10 GiB of which 3.74 GiB is free. Process 3089351 has 75.35 GiB memory in use. Of the allocated memory 63.90 GiB is allocated by PyTorch, and 10.78 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by bsandmg** [comment]
Prediction failed.

Not enough memory available to process your request. Try reducing the size or number of any file inputs or outputs.
More details
CUDA out of memory. Tried to allocate 15.00 GiB. GPU 0 has a total capacity of 79.10 GiB of which 3.74 GiB is free. Process 3089351 has 75.35 GiB memory in use. Of the allocated memory 63.90 GiB is allocated by PyTorch, and 10.78 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by mattt** [comment]
Hi @bsandmg. This looks like an error in the model rather than the Python client. If CUDA is running out of memory, then the problem is most likely that the model is configured to run on hardware that isn't supported. My advice would be to reach out to the owner of the model for help.
