### ISSUE TITLE
"ReplicateError 404 The requested resource could not be found" 30 minutes after creation of training

### ISSUE THREAD

**Issue by detkov** [replicate/replicate-python#352]
I've started a training of `ostris/flux-dev-lora-trainer:885394e6a31c6f349dd4f9e6e7ffbabd8d9840ab2559ab78aed6b2451ab2cfef` via API using `replicate.trainings.create`. 

All the previous times my attempts were successful and the queue time of these predictions was measured in ms, however, this training was queued for more than 30 minutes. During these 30 minutes, I was able to call `replicate.predictions.get` by the training id, it's response was:
```
Prediction(id='xxx', model='ostris/flux-dev-lora-trainer', version='885394e6a31c6f349dd4f9e6e7ffbabd8d9840ab2559ab78aed6b2451ab2cfef', status='starting', input={<some input here>}, output=None, logs='', error=None, metrics=None, created_at='2024-09-17T13:58:23.991Z', started_at=None, completed_at=None, urls={'cancel': 'https://api.replicate.com/v1/predictions/xxx/cancel', 'get': 'https://api.replicate.com/v1/predictions/xxx'})
```
Using the obtained `Prediction` object, I could cancel it.  
But exactly 30 minutes after the creation of the training, the answer from `replicate.predictions.get`
was the following:
```
Traceback (most recent call last):
  File "/home/ubuntu/core-api/test.py", line 76, in <module>
    asyncio.run(main())
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/core-api/test.py", line 45, in main
    await prediction.async_wait()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/studio-backend-p27wbUyn-py3.10/lib/python3.10/site-packages/replicate/prediction.py", line 154, in async_wait
    await self.async_reload()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/studio-backend-p27wbUyn-py3.10/lib/python3.10/site-packages/replicate/prediction.py", line 232, in async_reload
    updated = await self._client.predictions.async_get(self.id)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/studio-backend-p27wbUyn-py3.10/lib/python3.10/site-packages/replicate/prediction.py", line 367, in async_get
    resp = await self._client._async_request("GET", f"/v1/predictions/{id}")
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/studio-backend-p27wbUyn-py3.10/lib/python3.10/site-packages/replicate/client.py", line 95, in _async_request
    _raise_for_status(resp)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/studio-backend-p27wbUyn-py3.10/lib/python3.10/site-packages/replicate/client.py", line 385, in _raise_for_status
    raise ReplicateError.from_response(resp)
replicate.exceptions.ReplicateError: ReplicateError Details:
status: 404
detail: The requested resource could not be found.
```
Same with any request to the given ID. Nevertheless, I could see this training via the replicate site: active and queued. Thus, python API and site are somehow different.

As I understand, there is some HTTP API timeout, possibly depending on the `created_at` and `started_at` of the `get` response...

So my question is: how to make this work as it have to be working? Or do I have to measure 29 minutes and cancel tasks while I can to avoid this behavior?

P.S. `replicate==0.33.0`

**Comment by Clement-Lelievre** [comment]
Hi @detkov 

Did you solve it eventually?
I’m having kind of the same issue (with an inference though)
